name: CI/CD Pipeline for AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version of the checkout action

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2  # Use the latest version of the AWS CLI configuration action
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Correctly reference the secret
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Correctly reference the secret
        aws-region: eu-central-1  # Ensure this is the correct region for your S3 bucket

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://itsaws.com --exclude ".git/*" --delete
