name: CI/CD Pipeline for AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIAUJYWWRXW7ZMHJ6UO }}  # Ensure this matches your secret name
        aws-secret-access-key: ${{ secrets.NlwizhemQ2JCAQ0fNttZIsVQh2LfTdhASsXSFV/o }}  # Ensure this matches your secret name
        aws-region: eu-central-1  # Change to your desired region

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://itsaws --exclude ".git/*" --delete
